/*
 * U-Haul Snowflake Intelligence Demo - Table Creation
 * 
 * This script creates the core tables for U-Haul business operations:
 * - VEHICLES: Fleet inventory (trucks, trailers, equipment)
 * - CUSTOMERS: Customer information and profiles
 * - LOCATIONS: U-Haul locations and dealerships
 * - RENTALS: Rental transactions and agreements
 * - VEHICLE_TELEMETRY: Real-time vehicle usage and performance data
 * - MAINTENANCE_EVENTS: Vehicle maintenance and service records
 * - EQUIPMENT_INVENTORY: Additional equipment (dollies, blankets, etc.)
 * 
 * Prerequisites: Run 00_setup.sql first
 */

-- Ensure we're in the right context
USE WAREHOUSE UHAUL_DEMO_WH;
USE DATABASE UHAUL_DEMO;
USE SCHEMA RAW_DATA;

-- LOCATIONS: U-Haul pickup/dropoff locations
CREATE OR REPLACE TABLE LOCATIONS (
    LOCATION_ID VARCHAR(20) PRIMARY KEY,
    LOCATION_NAME VARCHAR(200) NOT NULL,
    ADDRESS VARCHAR(500),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    ZIP_CODE VARCHAR(20),
    COUNTRY VARCHAR(50) DEFAULT 'USA',
    LATITUDE DECIMAL(10,8),
    LONGITUDE DECIMAL(11,8),
    LOCATION_TYPE VARCHAR(50), -- 'Company Store', 'Dealer', 'U-Box Container'
    PHONE VARCHAR(20),
    HOURS_OF_OPERATION VARCHAR(200),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- VEHICLES: Fleet inventory
CREATE OR REPLACE TABLE VEHICLES (
    VEHICLE_ID VARCHAR(20) PRIMARY KEY,
    VIN VARCHAR(17) UNIQUE,
    VEHICLE_TYPE VARCHAR(50) NOT NULL, -- 'Pickup Truck', 'Cargo Van', 'Moving Truck', 'Trailer'
    VEHICLE_SUBTYPE VARCHAR(50), -- '10ft', '15ft', '20ft', '26ft', 'Cargo Trailer', 'Utility Trailer'
    MAKE VARCHAR(50),
    MODEL VARCHAR(50),
    YEAR INTEGER,
    LICENSE_PLATE VARCHAR(20),
    CURRENT_LOCATION_ID VARCHAR(20),
    VEHICLE_STATUS VARCHAR(30) DEFAULT 'Available', -- 'Available', 'Rented', 'Maintenance', 'Out of Service'
    MILEAGE INTEGER DEFAULT 0,
    FUEL_TYPE VARCHAR(20) DEFAULT 'Gasoline', -- 'Gasoline', 'Diesel', 'Electric'
    CARGO_CAPACITY_CUBIC_FEET INTEGER,
    MAX_LOAD_WEIGHT_LBS INTEGER,
    DAILY_RATE DECIMAL(8,2),
    MILEAGE_RATE DECIMAL(5,3), -- Rate per mile
    ACQUISITION_DATE DATE,
    LAST_MAINTENANCE_DATE DATE,
    NEXT_MAINTENANCE_DUE_MILEAGE INTEGER,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (CURRENT_LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
);

-- CUSTOMERS: Customer information
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(200),
    PHONE VARCHAR(20),
    DATE_OF_BIRTH DATE,
    DRIVERS_LICENSE_NUMBER VARCHAR(50),
    DRIVERS_LICENSE_STATE VARCHAR(50),
    ADDRESS VARCHAR(500),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    ZIP_CODE VARCHAR(20),
    COUNTRY VARCHAR(50) DEFAULT 'USA',
    CUSTOMER_SINCE DATE,
    CUSTOMER_TIER VARCHAR(20) DEFAULT 'Standard', -- 'Standard', 'U-Haul Pro', 'Business'
    TOTAL_RENTALS INTEGER DEFAULT 0,
    TOTAL_SPENT DECIMAL(10,2) DEFAULT 0.00,
    CREDIT_SCORE_RANGE VARCHAR(20), -- '300-579', '580-669', '670-739', '740-799', '800-850'
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- EQUIPMENT_INVENTORY: Additional rental equipment
CREATE OR REPLACE TABLE EQUIPMENT_INVENTORY (
    EQUIPMENT_ID VARCHAR(20) PRIMARY KEY,
    EQUIPMENT_TYPE VARCHAR(50) NOT NULL, -- 'Dolly', 'Furniture Pad', 'Tie Down', 'Box', 'Tape'
    EQUIPMENT_NAME VARCHAR(100),
    LOCATION_ID VARCHAR(20),
    QUANTITY_AVAILABLE INTEGER DEFAULT 0,
    DAILY_RATE DECIMAL(6,2),
    REPLACEMENT_COST DECIMAL(8,2),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
);

-- RENTALS: Rental transactions
CREATE OR REPLACE TABLE RENTALS (
    RENTAL_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    VEHICLE_ID VARCHAR(20) NOT NULL,
    PICKUP_LOCATION_ID VARCHAR(20) NOT NULL,
    DROPOFF_LOCATION_ID VARCHAR(20),
    RENTAL_START_DATE TIMESTAMP NOT NULL,
    RENTAL_END_DATE TIMESTAMP,
    PLANNED_RETURN_DATE TIMESTAMP,
    ACTUAL_RETURN_DATE TIMESTAMP,
    START_MILEAGE INTEGER,
    END_MILEAGE INTEGER,
    MILES_DRIVEN INTEGER,
    RENTAL_DURATION_HOURS INTEGER,
    BASE_RATE DECIMAL(8,2),
    MILEAGE_CHARGES DECIMAL(8,2) DEFAULT 0.00,
    EQUIPMENT_CHARGES DECIMAL(8,2) DEFAULT 0.00,
    FUEL_CHARGES DECIMAL(8,2) DEFAULT 0.00,
    LATE_FEES DECIMAL(8,2) DEFAULT 0.00,
    DAMAGE_FEES DECIMAL(8,2) DEFAULT 0.00,
    TOTAL_AMOUNT DECIMAL(10,2),
    PAYMENT_METHOD VARCHAR(30), -- 'Credit Card', 'Debit Card', 'Cash', 'Corporate Account'
    RENTAL_STATUS VARCHAR(30) DEFAULT 'Active', -- 'Reserved', 'Active', 'Completed', 'Cancelled'
    RESERVATION_CHANNEL VARCHAR(30), -- 'Website', 'Mobile App', 'Phone', 'In-Store'
    CUSTOMER_RATING INTEGER, -- 1-5 stars
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLES(VEHICLE_ID),
    FOREIGN KEY (PICKUP_LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID),
    FOREIGN KEY (DROPOFF_LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
);

-- VEHICLE_TELEMETRY: Real-time vehicle usage and performance data
CREATE OR REPLACE TABLE VEHICLE_TELEMETRY (
    TELEMETRY_ID VARCHAR(30) PRIMARY KEY,
    VEHICLE_ID VARCHAR(20) NOT NULL,
    RENTAL_ID VARCHAR(20),
    TIMESTAMP TIMESTAMP NOT NULL,
    LATITUDE DECIMAL(10,8),
    LONGITUDE DECIMAL(11,8),
    SPEED_MPH INTEGER,
    ENGINE_RPM INTEGER,
    FUEL_LEVEL_PERCENT INTEGER,
    ENGINE_TEMPERATURE_F INTEGER,
    ODOMETER_READING INTEGER,
    HARSH_BRAKING_EVENT BOOLEAN DEFAULT FALSE,
    HARSH_ACCELERATION_EVENT BOOLEAN DEFAULT FALSE,
    SPEEDING_EVENT BOOLEAN DEFAULT FALSE,
    IDLE_TIME_MINUTES INTEGER DEFAULT 0,
    FUEL_CONSUMPTION_RATE DECIMAL(5,2), -- Miles per gallon
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLES(VEHICLE_ID),
    FOREIGN KEY (RENTAL_ID) REFERENCES RENTALS(RENTAL_ID)
);

-- MAINTENANCE_EVENTS: Vehicle maintenance and service records
CREATE OR REPLACE TABLE MAINTENANCE_EVENTS (
    MAINTENANCE_ID VARCHAR(20) PRIMARY KEY,
    VEHICLE_ID VARCHAR(20) NOT NULL,
    MAINTENANCE_TYPE VARCHAR(50) NOT NULL, -- 'Preventive', 'Repair', 'Inspection', 'Recall'
    MAINTENANCE_CATEGORY VARCHAR(50), -- 'Engine', 'Transmission', 'Brakes', 'Tires', 'Body', 'Electrical'
    DESCRIPTION TEXT,
    SERVICE_DATE DATE NOT NULL,
    MILEAGE_AT_SERVICE INTEGER,
    LABOR_HOURS DECIMAL(5,2),
    PARTS_COST DECIMAL(8,2) DEFAULT 0.00,
    LABOR_COST DECIMAL(8,2) DEFAULT 0.00,
    TOTAL_COST DECIMAL(8,2),
    SERVICE_PROVIDER VARCHAR(100), -- 'U-Haul Service', 'Third Party Shop'
    TECHNICIAN_ID VARCHAR(20),
    VEHICLE_OUT_OF_SERVICE_HOURS INTEGER DEFAULT 0,
    NEXT_SERVICE_DUE_MILEAGE INTEGER,
    NEXT_SERVICE_DUE_DATE DATE,
    WARRANTY_CLAIM BOOLEAN DEFAULT FALSE,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLES(VEHICLE_ID)
);

-- RENTAL_EQUIPMENT: Junction table for equipment rented with vehicles
CREATE OR REPLACE TABLE RENTAL_EQUIPMENT (
    RENTAL_ID VARCHAR(20),
    EQUIPMENT_ID VARCHAR(20),
    QUANTITY INTEGER DEFAULT 1,
    DAILY_RATE DECIMAL(6,2),
    TOTAL_CHARGE DECIMAL(8,2),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (RENTAL_ID, EQUIPMENT_ID),
    FOREIGN KEY (RENTAL_ID) REFERENCES RENTALS(RENTAL_ID),
    FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENT_INVENTORY(EQUIPMENT_ID)
);

-- Display table creation completion
SELECT 'U-Haul Demo Tables Created Successfully!' as STATUS,
       COUNT(*) as TABLES_CREATED
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'RAW_DATA' 
AND TABLE_CATALOG = 'UHAUL_DEMO';
